### ISSUE TITLE
Bug located in How-To Section

### ISSUE THREAD

**Issue by dnwillia-work** [pyansys/dev-guide#120]
### Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### Description of the bug

This link is wrong in the 'git' section:

<img width="784" alt="image" src="https://user-images.githubusercontent.com/18702052/174420452-afb17eb2-caf6-4cbc-9394-bbc209d2df94.png">

Seems to be cut and paste from the python section and sends you to the python site

### Steps To Reproduce

Just click on it

### Which Operating System are you using?

MacOS

### Which Python version are you using?

3.8

### Installed packages

n/a

**Comment by jorgepiloto** [comment]
Good catch @dnwillia! Solved by @MaxJPRey.
