### ISSUE TITLE
Add recommended configuration of Sphinx build options

### ISSUE THREAD

**Issue by PipKat** [pyansys/dev-guide#150]
### 📝 Description of the feature

@dnwillia-work thought it would be good to have the recommended configuration for Sphinx build options in the *PyAnsys Developer's Guide*. He said that Fluent's build options are here: [pyfluent/Makefile at main · pyansys/pyfluent (github.com)](https://github.com/pyansys/pyfluent/blob/main/doc/Makefile)
He then said that they use ``-W`` and that most repos should probably be using that.

### 🔗 Useful links and references

Fluent's Sphinx build options are here: [pyfluent/Makefile at main · pyansys/pyfluent (github.com)](https://github.com/pyansys/pyfluent/blob/main/doc/Makefile)

**Comment by dnwillia-work** [comment]
Thanks Kathy.  Yes, in particular I think `-W --keep-going` is useful.  This way you get all the warnings in the build log so you can inspect the log, fix everything and updated the PR.
