### ISSUE TITLE
Add version_requires documentation

### ISSUE THREAD

**Issue by akaszynski** [pyansys/dev-guide#152]
We need a consistent direction for backwards/forwards server support. Both PyDPF and PyMAPDL do this with:

https://github.com/pyansys/pydpf-core/blob/9a69bae039ef923bce68cc66a6303ab2b9f55c4c/ansys/dpf/core/check_version.py

I also would like to create a `ansys.helpers.versioning` library that contains these functions that we can reuse in multiple libraries.

**Comment by RobPasMue** [comment]
Working on this issue

**Comment by jorgepiloto** [comment]
The `ansys.helpers.versioning` library is being hosted in https://github.com/pyansys/pyansys-helpers-versioning.

**Comment by MaxJPRey** [comment]
> The `ansys.helpers.versioning` library is being hosted in https://github.com/pyansys/pyansys-helpers-versioning.

Thanks @jorgepiloto for creating the repo.
