### ISSUE TITLE
"Uploading to private PyPI using the command line" is incorrect

### ISSUE THREAD

**Issue by MaxJPRey** [pyansys/dev-guide#157]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

![image](https://user-images.githubusercontent.com/87315832/183509792-46838434-5008-4c5e-8b51-539b90214b2a.png)

The code block is incorrectly displayed.

### 📝 Steps to reproduce

N/A

### 💻 Which operating system are you using?

Windows

### 🐍 Which Python version are you using?

3.10

### 📦 Installed packages

```shell
Not necessary.
```

**Comment by jorgepiloto** [comment]
Good catch!
