### ISSUE TITLE
URL is incorrect in the "download from private PyPI" section

### ISSUE THREAD

**Issue by MaxJPRey** [pyansys/dev-guide#158]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

![image](https://user-images.githubusercontent.com/87315832/183605974-6bf72618-821f-4f41-abe0-d0364e61cf7b.png)

Single quotes should be removed around the `INDEX_URL`. Otherwise it causes an exception to be raised when downloading.

### 📝 Steps to reproduce

N/A

### 💻 Which operating system are you using?

Windows

### 🐍 Which Python version are you using?

3.10

### 📦 Installed packages

```shell
N/A
```

**Comment by jorgepiloto** [comment]
Thanks for opening this, @MaxJPRey.
