### ISSUE TITLE
Migrate to sphinx-design

### ISSUE THREAD

**Issue by jorgepiloto** [pyansys/dev-guide#182]
🐞 **Problem**
The [sphinx-design] library offers lots of features and new capabilities that we can take advantage of. For example, it includes tabs and panels among other features.

This means that we can get rid of [sphinx-panels] and [sphinx-tabs] by having all this features collected under the same library.

In addition, this may allow us to solve the dependencies issue in #135 and finally migrate to latest Sphinx version.

[sphinx-design]: https://sphinx-design.readthedocs.io/en/latest/
[sphinx-panels]: https://sphinx-panels.readthedocs.io/en/latest/
[sphinx-tabs]: https://sphinx-tabs.readthedocs.io/en/latest/

**Comment by jorgepiloto** [comment]
Hi @Revathyvenugopal162,
would you be interested in taking this issue?

**Comment by Revathyvenugopal162** [comment]
Yes. i will handle this issue.

**Comment by jorgepiloto** [comment]
Thanks a lot @Revathyvenugopal162 🚀

**Comment by MaxJPRey** [comment]
@jorgepiloto @Revathyvenugopal162 I am glad to see that with this library we will fix our doc dependencies issue.
