### ISSUE TITLE
Display of the "Logging" and "Documenting" section is incorrect.

### ISSUE THREAD

**Issue by MaxJPRey** [pyansys/dev-guide#191]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

In the dev-guide, the section named `Logging` and `Documenting` are not displayed properly.
The text is overlapping with the left panel listing the sections.

### 📝 Steps to reproduce

If you go to: https://dev.docs.pyansys.com/how-to/logging.html

Then scroll down, and you will get the following rendering:
![image](https://user-images.githubusercontent.com/87315832/194028173-3d86bd8c-31d1-4d27-a6f6-f587d273d4b0.png)

Same goes for documentation:

If you go to: https://dev.docs.pyansys.com/how-to/documenting.html

![image](https://user-images.githubusercontent.com/87315832/194028479-bec0b151-4760-46f5-90de-d66bd376235c.png)

### 💻 Which operating system are you using?

Windows

### 🐍 Which Python version are you using?

3.10

### 📦 Installed packages

```shell
N/A
```

**Comment by PipKat** [comment]
The Packaging topic in the How to section is also doing this.

**Comment by MaxJPRey** [comment]
@PipKat Hopefully https://github.com/ansys/ansys-sphinx-theme/pull/130 will fix all those issues.

**Comment by RobPasMue** [comment]
Looks like this has been resolved with ``ansys-sphinx-theme==0.6.1``
![image](https://user-images.githubusercontent.com/37798125/194256726-3e67f728-1824-459b-a759-8f1012e9156a.png)
![image](https://user-images.githubusercontent.com/37798125/194256882-b3d9e2ac-6ebd-4132-ab6c-c269afcfba11.png)
