### ISSUE TITLE
Rename `abstraction` section to `guidelines`

### ISSUE THREAD

**Issue by akaszynski** [pyansys/dev-guide#20]
Rename "Abstraction and Encapsulation" to "Guidelines" and then add the new logging guidelines to that. Make changes to:
https://github.com/pyansys/dev-guide/blob/main/doc/source/abstraction/index.rst

We might consider adding a section regarding packaging approaches, for example, using `pyproject.toml`, etc.

In this PR, consider moving https://dev.docs.pyansys.com/overview/dev_practices.html# to the new "Guidelines" section.

Also, change the order from "Overview", "Library Overview", "Guidelines" to "Overview", "Guidelines", "Library Overview"

**Comment by MaxJPRey** [comment]
@akaszynski The point about the new packaging section will be handled in a separate issue #21 .
