### ISSUE TITLE
Modify tab order

### ISSUE THREAD

**Issue by germa89** [pyansys/dev-guide#202]
### Description of the modifications

Shouldn't the ``Use`` be shown by default instead of ``Avoid``:

![image](https://user-images.githubusercontent.com/28149841/198058483-1f4e32c2-b129-4e53-ad74-67a100c19ada.png)

https://dev.docs.pyansys.com/coding-style/pep8.html

**Comment by MaxJPRey** [comment]
Agreed. We must revert the tabs.

**Comment by jorgepiloto** [comment]
Thanks for suggesting this, @germa89.

**Comment by RobPasMue** [comment]
Let me tackle this issue quickly :)

**Comment by germa89** [comment]
Thank you @RobPasMue !
