### ISSUE TITLE
Modify ...

### ISSUE THREAD

**Issue by PipKat** [pyansys/dev-guide#206]
### Description of the modifications

Sphinx image referenced in the "Documentation sources" section of file indicated below is not showing in the generated doc. I thought if someone was making a change, they could fix this issue. The image was showing back in mid-October because I have a screen capture taken there where it was present.

file: PyAnsys\dev-guide\doc\source\how-to/docurenting.rst
![image](https://user-images.githubusercontent.com/84872299/200928580-3667b1c5-da06-455d-acce-9c800075b175.png)

**Comment by PipKat** [comment]
I also saw in this same topic that we need to make "Deploy using a PAT" a title.

![image](https://user-images.githubusercontent.com/84872299/200930113-ddc8c87d-276e-4915-83a5-2c5d7b63cfa9.png)

**Comment by RobPasMue** [comment]
These problems have been solved:
* Image not showing:
![image](https://user-images.githubusercontent.com/37798125/210325530-385468b8-b756-48d4-a744-22a2735f2dd3.png)
* ``Deploy using a PAT`` is no longer a section after we moved to using PyAnsys actions for deployment. So, no longer needed to adapt.
