### ISSUE TITLE
Add public release documentation

### ISSUE THREAD

**Issue by akaszynski** [pyansys/dev-guide#232]
### 📝 Description of the feature

Add the steps to release a package to the public. Should include the following:
- Pre-release requirements. Draft: https://supreme-invention-8c3992a9.pages.github.io/
- Following steps:
  1. Upload to public [PyPI](https://pypi.org/). Optionally, upload to PyPI testing first using the `PYPI_TESTING_TOKEN`. Note: Both `PYPI_TOKEN` and `PYPI_TESTING_TOKEN` are only available to private and internal repositories, meaning that you must first manually upload to PyPI using the global token (either manually or automatically).
  2. Generate a package specific token for the [PyPI ansys account](https://pypi.org/user/ansys/). Override `PYPI_TOKEN` in the repository.
  3. Make GitHub repository public. This should make the GitHub pages public if the documentation is hosted in the same repository in (for example `gh-pages`). If documentation is hosted in a separate repository, that repo will have to be made public.

### 💡 Steps for implementing the feature

@jorgepiloto, improve the above description and add it to `dev-guide`.

**Comment by jorgepiloto** [comment]
Working on this.

**Comment by akaszynski** [comment]
> This could prevent people from releasing a package without legal approval.

You're probably right. Let's make sure we have individual tokens for each project before proceeding, but I agree that we should remove it.

Let's clearly document the release procedure so people know who they can go to.
