### ISSUE TITLE
Document CNAME

### ISSUE THREAD

**Issue by akaszynski** [pyansys/dev-guide#235]
### 📝 Description of the feature

Document valid CNAMES for pyansys.com

Right now we have the informal standard of docs.<product/service/library>.pyansys.com and we have great documentation of this at [DNS configuration](https://dev.docs.ansys.com/contents/ansys_best_practices/code_management/github/github_pages.html#dns-configuration)

Let's add part of that here within our dev documentation so we're consistent, and also clearly spell out who's responsible for adding the CNAME.

### DNS Takeover
Document the steps to take a DNS takeover.

CC @phxnsharp 

### 💡 Steps for implementing the feature

Reuse part of [DNS configuration](https://dev.docs.ansys.com/contents/ansys_best_practices/code_management/github/github_pages.html#dns-configuration).

**Comment by phxnsharp** [comment]
Given the things we learned today regarding how GitHub domain verification only works for immediate sub-domains, the guidance of <product/service/library>.docs.pyansys.com might be smarter. Then we don't have to verify each product subdomain.

**Comment by akaszynski** [comment]
If that's the case, we've got some redirects to handle. Wouldn't be the first time we changed a CNAME.

**Comment by RobPasMue** [comment]
Right now, at least in the "pyansys.com" DNS all (i.e. >95%) of our subdomains follow the <product/service/library>.docs.pyansys.com guidance, and not docs.<product/service/library>.pyansys.com

No redirects to handle @akaszynski - all our libraries are following the proper *.docs.pyansys.com approach

Regarding GitHub domain verification, I don't think it is properly working... see my comment on the MS Teams chat. Verifying the domain at an org level does not ensure that other external users can take over subdomains that are not being used.

**Comment by phxnsharp** [comment]
> Regarding GitHub domain verification, I don't think it is properly working

Alex and Ryan are working on documenting the procedure to validate. It is in a different place in settings. It only works for the exact subdomain and immediate children. Ryan is creating CI rules on their side to ensure we do this right moving forward.

**Comment by phxnsharp** [comment]
Ironically, mine is probably the broken 5%: https://docs.variableinterop.pyansys.com/. Guess I better fix that.

**Comment by RobPasMue** [comment]
> > Regarding GitHub domain verification, I don't think it is properly working
> 
> Alex and Ryan are working on documenting the procedure to validate. It is in a different place in settings. It only works for the exact subdomain and immediate children. Ryan is creating CI rules on their side to ensure we do this right moving forward.

Thanks @phxnsharp for the explanation! I wasn't sure if you had kept doing trials yesterday or not, that's why I went ahead and tried it this morning. I'll wait for the documentation to be shared before removing my trials.

**Comment by RobPasMue** [comment]
Let me start working on this @jorgepiloto - I'll ping you as reviewer in any case. This is high priority.
