### ISSUE TITLE
Clarify location of 'versions.json' for the multi-version feature

### ISSUE THREAD

**Issue by greschd** [pyansys/dev-guide#244]
In this part of the docs:
![image](https://user-images.githubusercontent.com/5692808/213495568-e58ed4e8-9169-4143-b117-db7d8662fe88.png)
it's unclear whether the `versions.json` should be at the top-level, or in the `release/` directory.

Looking at existing projects, it seems "in the `release/` directory" is the correct answer.

**Comment by jorgepiloto** [comment]
Thanks for opening this issue, @greschd. I agree with you, description is wrong. Let me fix it.
