### ISSUE TITLE
Broken links to pyansys dev guide in most of pyansys documentation. 

### ISSUE THREAD

**Issue by Revathyvenugopal162** [pyansys/dev-guide#267]
### Description of the modifications

In most of the pyansys docs, the link to developer guide is broken because of the new layout of the pyansys/actions. Examples: 
https://dev.docs.pyansys.com/how-to/contributing.html should replace by https://dev.docs.pyansys.com/dev/how-to/contributing.html, in most of the contributing guide of respective docs.

One possible solution is Deploying the docs directly to gh pages, instead of ``dev`` folder, so use custom docs build rather than building with pyansys/actions. Redirection of main page will not work, for child pages.

Pinging here @jorgepiloto

**Comment by jorgepiloto** [comment]
I agree. Knowing that our "dev-guide" is deployed everytime we merged something, multi-version does not make sense for this guide.

**Comment by jorgepiloto** [comment]
Let me address this issue. I want to take advantage to clean a bit the project.

**Comment by PipKat** [comment]
On the documentation style page (https://dev.docs.pyansys.com/dev/doc-style/index.html), the link to MAPDL examples is broken.  How should the URL look now that we want it to point to the stable version? I wanted to try out the "Edit this page" button but wasn't sure how to fix the broken URL.
