### ISSUE TITLE
Replace all pyansys.support references with pyansys.core ones

### ISSUE THREAD

**Issue by jorgepiloto** [pyansys/dev-guide#271]
🐞 **Problem**
As suggested internally, let us replace all the references to the `pyansys.support@ansys.com` with the `pyansys.core@ansys.com` email.

**Comment by PipKat** [comment]
@jorgepiloto @RobPasMue Do we want to replace with the pyansys.core@ansys.com email address or direct them to the dev portal? The ultimate objective wasn't clear to me.

**Comment by RobPasMue** [comment]
I think in this case, [pyansys.core@ansys.com](mailto:pyansys.core@ansys.com) email address. It's mostly for requesting tokens and stuff like that.

**Comment by PipKat** [comment]
> I think in this case, [pyansys.core@ansys.com](mailto:pyansys.core@ansys.com) email address. It's mostly for requesting tokens and stuff like that.

@RobPasMue or @jorgepiloto Makes sense! I see Jorge already did the changes in this guide. Is this something that you want me to search for and replace in other public libraries?
