### ISSUE TITLE
feat/ online version

### ISSUE THREAD

**Issue by germa89** [pyansys/dev-guide#37]
I believe we should have this document online maybe under:

``dev-docs.pyansys.com``

Or similar. 

It should not be very difficult to do, and I'm to take the lead on this.

**Comment by greschd** [comment]
Isn't this https://dev.docs.pyansys.com/ ?

**Comment by germa89** [comment]
Dominik, you are the best!

I will propose to add it to the repo readme

**Comment by germa89** [comment]
I would also add it to this: https://docs.pyansys.com/
