### ISSUE TITLE
New Packaging Style guide

### ISSUE THREAD

**Issue by jorgepiloto** [pyansys/dev-guide#62]
🐞 **Improve Library Overview chapter**

Although the [Library Overview chapter] holds various sections, those are not deeply explained. In addition, there are "duplicated" explanations/guidelines which could be collected under common sections or files.

💡 **Solutions to be discussed**

Here are some proposed solutions to unify some of the concepts presented in the chapter:

- [ ] **Unify required files and packaging sections**
The [Library Overview chapter] contains "duplicated explanations". As an example, the [Setup File], [README File] and [License File] sections are referenced in the [Packaging] one under the [Required Files] subsection. The [Packaging] guidelines are being updated in #44, so this is blocked before those changes are merged.

- [ ] **Unify library, project and repository sections**
In addition to previous situation, [Library Structure] section, [Project, Repository, and Library Names] section, and [Repository Directory Structure] are a bit similar. What if we combined those into a "Project Repository" section were properly listing out main differences across a library, project and a repository.

- [x] **Add references to ansys-templates**
The [ansys-templates tool] supports inheritance and is deep tested, increasing the stability of the tool. References to [ansys-templates tool] must be done in the [Library Template] section. The guidelines and the ansys-templates must be compliant regarding the minimum required files to setup a Python Package.

[Library Overview chapter]: https://dev.docs.pyansys.com/library_description/index.html
[Setup File]: https://dev.docs.pyansys.com/library_description/setup_file.html
[README File]: https://dev.docs.pyansys.com/library_description/readme_file.html
[LICENSE File]: https://dev.docs.pyansys.com/library_description/license.html
[Packaging]: https://dev.docs.pyansys.com/library_description/packaging.html
[Required Files]: https://dev.docs.pyansys.com/library_description/packaging.html#required-files
[Library Structure]: https://dev.docs.pyansys.com/library_description/library_structure.html
[Project, Repository, and Library Names]: https://dev.docs.pyansys.com/library_description/library_names.html
[Repository Directory Structure]: https://dev.docs.pyansys.com/library_description/repo_directory_structure.html
[Library Template]: https://dev.docs.pyansys.com/library_description/template.html
[ansys-templates tool]: https://github.com/pyansys/ansys-templates

**Comment by akaszynski** [comment]
#44 is merged, please proceed with unifying the required files and packaging sections. Let's shoot for poetry for now, but also mention that `setup.py` with `setuptools` is also an option.
