### ISSUE TITLE
The release process contradicts the branching model

### ISSUE THREAD

**Issue by plule-ansys** [pyansys/dev-guide#79]
The release process described [here](https://dev.docs.pyansys.com/guidelines/dev_practices.html#release-procedures) let readers think that release branches are then merged into main. However in trunk based development, the release branches are never merged, they stay independent, and any change there is either versioning, or cherry-pick of fixes from `main`.

This section should split more clearly what happens in the release branch and what happens in the `main` branch.

A second pedantic issue is that it describes hot fixes to be pushed in the release branch, where it should actually be first fixed in the main branch, then cherry-picked in the release branch.

**Comment by akaszynski** [comment]
Fixed in #80. Thanks!
