### ISSUE TITLE
Configure venv scripts are outdated

### ISSUE THREAD

**Issue by jorgepiloto** [pyansys/dev-guide#84]
Both `configure_venv.bat` and `configure_venv.sh` point to a `requirements_style.txt` file that no longer exists.

**Comment by jorgepiloto** [comment]
Would you like to address this, @Revathyvenugopal162?

**Comment by Revathyvenugopal162** [comment]
yes, i would like review some pull request and issues as much possible so that i will be more familiar with the standards and GitHub pull requests because i am new to it.

**Comment by jorgepiloto** [comment]
Thanks for taking this, @Revathyvenugopal162. I think we can start by removing line 6 in `configure_venv.bat`:

https://github.com/pyansys/dev-guide/blob/a02c0e4cddbd35473c3c580de1bbf8dd8e9f90e5/configure_venv.bat#L1-L7

and line 5 in `configure_venv.sh`:

https://github.com/pyansys/dev-guide/blob/a02c0e4cddbd35473c3c580de1bbf8dd8e9f90e5/configure_venv.sh#L1-L6
