### ISSUE TITLE
Add blacken-docs to pre-commit

### ISSUE THREAD

**Issue by jorgepiloto** [pyansys/dev-guide#98]
### Description of the feature

Something I discovered while working on #64 was that some of the code snippets were not compliant with the code style guidelines. 

After looking for a solution, I came across [blacken-docs](https://github.com/asottile/blacken-docs/), which turned out to be extremely useful.

### Steps for implementing the feature

The main idea behind this new feature would be to add this doc style checker to our current style tests via pre-commit.

### Useful links and references

Blacken-docs: https://github.com/asottile/blacken-docs/

**Comment by jorgepiloto** [comment]
⚠️ *Notice some of our examples are non-style compliant on purpose*

This is done to educate others on what to do and avoid. As long as `blacken-docs` can ignore these files, we can implement this feature.

**Comment by MaxJPRey** [comment]
@jorgepiloto I will implement it for [PyAEDT](https://github.com/pyansys/pyaedt).

**Comment by RobPasMue** [comment]
Working on this. I will also implement [pre-commit.ci](https://pre-commit.ci/) in this task if it's okay with you all.
